version: '3'
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command: --configFile=/etc/traefik/traefik.yml
    ports:
      - '80:80' # Open this port on VPS (or change it for better security)
      - '443:443' # Open this port on VPS (or change it for better security)
      - '8080:8080' # (Optional) port for Trafik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./mycoffee.json:/mycoffee.json # myCoffee resolver
      # - ./domain2-acme.json:/domain2-acme.json # Second resolver
    networks:
      - mycoffee-network
      # - domain2-network

networks:
  mycoffee-network:
    external: true # You need to create this network first
  # domain2-network:
  #   external: true
