entryPoints:
  web:
    address: ':80'
    http:
      redirections: # Redirect http -> https
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'

# (Optional) Use a custom certificate, see certificate.sh
# tls:
#   certificates:
#     - certFile: ../localhost.crt
#       keyFile: ../localhost.key

certificatesResolvers:
  myCoffeeResolver:
    acme:
      email: contact@mycoffee.shop
      storage: mycoffee.json
      httpChallenge:
        entryPoint: web
  # domain2Resolver:
  #   acme:
  #     email: me@gmail.com
  #     storage: domain2-acme.json
  #     httpChallenge:
  #       entryPoint: web

providers:
  docker:
    exposedByDefault: false
